version: '3.8'

services:
  web:
    container_name: web
    build: ./services/web
    volumes:
      - ./files:/files
    expose:
      - 8000
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 app:app

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      target: prod
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./files:/files
    ports:
      - 80:80
      - 443:443

  mongo:
    image: mongo
    volumes:
      - ./db:/data/db
    expose:
      - 27017